[workspace]
resolver = "2"
members = [
    "packages/ducrs",
    "packages/ducpdf/src/duc2pdf",
    "packages/ducsvg/src/pdf2svg",
]

[workspace.dependencies]
duc = { version = "1" }

[profile.release]
lto = true
opt-level = "s"