[project]
name = "ducpy"
dynamic = ["version"]
description = "The library for the Duc 2D CAD file format"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "nanoid>=2.0.0",
]

license = { text = "MIT" }

authors = [
    { name = "Ducflair", email = "support@ducflair.com" },
    { name = "Jorge Soares" }
]

classifiers = [
    "License :: OSI Approved :: MIT License",
]

[project.urls]
"Homepage" = "https://duc.ducflair.com"
"Source" = "https://github.com/ducflair/duc/tree/main/packages/ducpy"
"Documentation" = "https://ducflair.github.io/duc/reference/python/"
"Package Index" = "https://ducflair.github.io/duc/simple/ducpy/"

[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[tool.maturin]
manifest-path = "crate/Cargo.toml"
python-source = "src"
module-name = "ducpy_native"
include = [
    { path = "LICENSE", format = "sdist" }
]

[tool.setuptools]
[tool.setuptools.packages.find]
where = ["src"]

[dependency-groups]
dev = [
    "furo>=2024.8.6",
    "sphinx>=8.1.3",
    "sphinx-autoapi>=3.6.0",
    "pytest>=8.3.5",
    "numpy>=1.20.0",
    "rich>=13.0.0",
]


[tool.pytest.ini_options]
testpaths = ["src/tests"]
python_files = "test_*.py"
addopts = "-vv"
