name: Release ducsvg

on:
  workflow_dispatch:
  push:
    branches: [main, next, dev]
    paths:
      - 'packages/ducsvg/**'
      - 'package.json'

permissions:
  contents: write
  issues: write
  pull-requests: write
  id-token: write

jobs:
  release_ducsvg:
    runs-on: ubuntu-latest
    concurrency:
      group: release-ducsvg
      cancel-in-progress: false
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref_name }}
          persist-credentials: true
      - name: Set Git User
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: "latest"
      - name: Install deps
        run: bun install
      - name: Build
        run: bun ducsvg:build

      - name: Prepare workspace dependencies for publish
        run: node scripts/fix-workspace-deps.mjs packages/ducsvg/package.json
        
      - name: Setup release environment
        id: setup-release-environment
        uses: ./.github/actions/simulate-main-environment
        with:
          current-branch: ${{ github.ref_name }}
          package-name: ducsvg

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # DEBUG: "semantic-release:*" # For verbose logging
        working-directory: ./packages/ducsvg
        run: npx semantic-release ${{ steps.setup-release-environment.outputs.release-mode }}
